---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge DKAM

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - release-*
    paths:
      - "dkam/**"

permissions:
  contents: read

jobs:
  post-merge-pipeline:
    permissions:
      contents: read
      security-events: write
      id-token: write
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge.yml@0d87105b01c38f6e9aa373871337b8b836237b19  # 2026.0.10
    with:
      bootstrap_tools: "all,golangci-lint2"
      run_version_check: true
      run_dep_version_check: true
      run_build: true
      run_docker_build: false
      run_docker_push: true
      run_version_tag: true
      run_version_dev: true
      prefix_tag_separator: "/"
      project_folder: "dkam"
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
      NO_AUTH_ECR_PUSH_USERNAME: ${{ secrets.NO_AUTH_ECR_PUSH_USERNAME }}
      NO_AUTH_ECR_PUSH_PASSWD: ${{ secrets.NO_AUTH_ECR_PUSH_PASSWD }}
      MSTEAMS_WEBHOOK: ${{ secrets.TEAMS_WEBHOOK }}
