---
# SPDX-FileCopyrightText: (C) 2025 Intel Corporation
# SPDX-License-Identifier: Apache-2.0

name: Post-Merge Scorecard CI

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  call-scorecard:
    permissions:
      security-events: write   # required for SARIF upload
      id-token: write
      contents: read
    uses: open-edge-platform/orch-ci/.github/workflows/post-merge-scorecard.yml@a21d1491d0d456d44b386515f74885632a9536a1  # 2026.0.8
    with:
      project_folder: "."
    secrets:
      SYS_EMF_GH_TOKEN: ${{ secrets.SYS_EMF_GH_TOKEN }}
